### ISSUE TITLE
Error uploading a Media file

### ISSUE THREAD

**Issue by Falteri** [zerocrates/AltText#1]
Whith Omeka 1.2.0 and AltText module I get this error while uploading an item media file:

A new entity was found through the relationship 'AltText\Entity\AltText#media' that was not configured to cascade persist operations for entity: Omeka\Entity\Media@000000003c262f180000000058caf073. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Omeka\Entity\Media#__toString()' to get a clue.

**Comment by zerocrates** [comment]
Hmmmm, that... shouldn't happen.

I think this error is basically masking an issue with the media upload you did (you only get this error when you've created a record and then it ultimately doesn't get saved), but... the module already contains code that should prevent this error from happening.

Can you reproduce the error? Does it happen with _all_ media or just a particular file, etc.?

**Comment by zerocrates** [comment]
This should now be resolved with version 1.0.2 of the AltText module.
