### ISSUE TITLE
Context-specific alt text

### ISSUE THREAD

**Issue by triplingual** [zerocrates/AltText#3]
What would it take to incorporate this module's editing functionality in blocks, to allow for context-specific alt text? The accessibility pros at my uni say that good accessibility practice is for alt text of an image used as link content to declare the link target.

Doing that would mean needing to set alt text differently in a Media Embed block (where a still image links to the Item page) from the Item page (where the image links to its Media page) as well as from the Media page (where our images link to their files). I haven't set foot in the world of module code, so I don't know how complicated this would be.

it doesn't look like this has been discussed on the forums, but I'm happy to take the conversation there if it's more appropriate.

**Comment by zerocrates** [comment]
Hmm, that's a tricky one.

In terms of the way the module currently works, it's rough since everything is assumed to have a single alt text for all contexts. So there's simple things like the database model not allowing multiple alt texts per record, but that's not insurmountable of course. If the idea is pulling text out of the metadata that's less of an issue, as well.

It's a little iffier getting the correct context to decide what text to use. You could look at the page you're on and try to decide that way, though that's likely to be a brittle solution.

**Comment by triplingual** [comment]
Totally. This is prompted partly by wanting to write locally specific doco for our users and then strengthened by talking with our web accessibility team. That team tells me that the alt for an image used as a link (which will be all uses of Media on a Site Page, yes?) should be the target for the link so adaptive tech compiling the links will have a readable and useful list. This target is settable in Site settings.

I have no idea how it would be done and how nontrivial it would be, but there's a place (+/- what you mention) to put a caption on a piece of media when adding it as an attachment to a block. That seems like the best (UX-wise) place to put the ability to give that attachment locally specific alt text. In the world of rainbows and unicorns, an alt text field in that attachment selection drawer would default to the alt text added at the Media level so that if it's fine the author doesn't need to do anything.

We've arrived at telling our people to use "See more about [appropriate media/item title]" as the alt text because that phrasing is mostly semantically valid for the 3 possible uses of Media I know of.

**Comment by zerocrates** [comment]
So, the handling of the `alt` parameter by the AltText module already kind of allows what you're talking about: basically, if you've specified an `alt` already in your call to show a thumbnail or render an image, that one will get used. Only where there isn't an alt specified will the module use the one that's configured for the media.

The missing piece would be the part where you can set an alt in the UI when attaching the media on the backend. Using an alt that's calculated from metadata or in some other "automated" way would already be possible with a custom block that just passes along an `alt` parameter when displaying the images.

**Comment by triplingual** [comment]
Thanks for that explanation. I'm still shallow/green enough with Omeka S development and my org is leery of writing custom code, so it's unlikely we'll go that route. Good to know we could if we wanted to.

One question, though: Using a custom block for this would seem to me to mean writing shadow versions of the Media Embed, Item Showcase, and Item with Metadata blocks. Am I understanding correctly? Or is there a way, in principle, to write a custom block that introduces something into each of those?

**Comment by zerocrates** [comment]
Closing in favor of omeka/omeka-s#1711
